name: Check Approve Owner repository

on:
  pull_request_review:
    types: [submitted]
    branches: [homolog, prod]

jobs: 
  valid_owner:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    env:
      repo: ${{ github.repository }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Validate PR Owner
        env:
          author: ${{ github.event.review.user.login }}
        run: |
          perm=$(gh api "repos/$repo/collaborators/$author/permission" --jq '.permission')
          echo "perm=$perm" >> $GITHUB_ENV
          if [[ $perm != 'admin' ]]; then
              echo "::error:: Reviewer NÃO é um admin, solicitar review de um Admin para aprovação"
          else
              echo "Reviewer é um admin, PR liberado para ser mergeado."
          fi
